### ISSUE TITLE
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDeviceFunction: invalid device function

### ISSUE THREAD

**Issue by lizekui** [pschaldenbrand/StyleCLIPDraw#2]
Hi this research is really fantastic and exciting !
According Colab instruction, when I run 
`img = style_clip_draw('A man is watching TV', 'https://raw.githubusercontent.com/pschaldenbrand/StyleCLIPDraw/master/images/fruit.jpg',\
                          num_iter=1000, style_opt_freq=5, style_opt_iter=50)
show_img(img)`

the runtime return 

`Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth
100%
528M/528M [00:05<00:00, 103MB/s]
`
`
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-c7386fef0808> in <module>()
----> 1 img = style_clip_draw('A man is watching TV', 'https://raw.githubusercontent.com/pschaldenbrand/StyleCLIPDraw/master/images/fruit.jpg',                          num_iter=1000, style_opt_freq=5, style_opt_iter=50)
      2 show_img(img)
`
`
4 frames
/usr/local/lib/python3.7/dist-packages/diffvg-0.0.1-py3.7-linux-x86_64.egg/pydiffvg/render_pytorch.py in backward(ctx, grad_img)
    707                       use_prefiltering,
    708                       diffvg.float_ptr(eval_positions.data_ptr()),
--> 709                       eval_positions.shape[0])
    710         time_elapsed = time.time() - start
    711         global print_timing
`
`
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDeviceFunction: invalid device function`

And rerun twice or triple also show same info.
Can this work's expert help me ? Thanks!

**Comment by pschaldenbrand** [comment]
Hi @lizekui Thanks for your interest!

I believe the error has to do with the GPU that Colab has assigned to you.  The notebook needs to be run with a T4, P4, P100, or V100 GPU (K80 will not work, unfortunately).  If you are a Colab Pro user, these GPUs will be frequently assigned to you.  If you are a free user, you may have to restart the machine a few times until you get assigned one (Runtime -> manage sessions -> terminate the session -> start a new session and run all).  You can see what GPU you are assigned in the second cell.  Sorry for this inconvenience :( I will update the information in the notebook to reflect this.

**Comment by lizekui** [comment]
Hi @pschaldenbrand  sooo glad to have your reply! Thanks a lot!
I am really interested in this repo, and I subscribe Colab Pro according your suggestion~ indeed switch P100 GPU and no more received `cudaErrorInvalidDeviceFunction: invalid device function` error!

But unfortunately, another error show when I run
 `img = style_clip_draw('A man is watching TV', 'https://raw.githubusercontent.com/pschaldenbrand/StyleCLIPDraw/master/images/fruit.jpg',\
                          num_iter=1000, style_opt_freq=5, style_opt_iter=50)`

error is 

`/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    147     Variable._execution_engine.run_backward(
    148         tensors, grad_tensors_, retain_graph, create_graph, inputs,
--> 149         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
    150 
    151 
`
`
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered`

And how to solve it ? Can you help me again? hah Thanks!

**Comment by pschaldenbrand** [comment]
I think this is a result of a pytorch versioning issue.  Perhaps Colab has changed their default torch version.  Could you please try to run:
`!pip install torch~=1.10.0 torchvision~=0.10.0`
You may need to restart the notebook after running that code in a new cell.

**Comment by hepesu** [comment]
The versions are critical. Python 3.7 + CUDA 10.2 + Pytorch 1.7.1 works for me.

PyTorch < 1.7 causes issue from `clip`, and CUDA>10 may cause CUDA memory issue from `diffvg`. And K80 will not work, at least T4.

**Comment by lizekui** [comment]
> I think this is a result of a pytorch versioning issue. Perhaps Colab has changed their default torch version. Could you please try to run: `!pip install --upgrade torch` You may need to restart the notebook after running that code in a new cell.

Oh this solution is really suitable for me! After upgrade torch, the code run normally! Thanks pschaldenbrand  alot! Your work is great imaginative!

btw torch version is, for the same problem reference~
`Torch version: 1.10.0+cu102`
