### ISSUE TITLE
Colab StyleCLIPDraw error 

### ISSUE THREAD

**Issue by mcanet** [pschaldenbrand/StyleCLIPDraw#5]
Using Colab pro with a GPU 0: Tesla P100-PCIE-16GB

Executing: 
```
img = style_clip_draw('A man is watching TV', 'https://raw.githubusercontent.com/pschaldenbrand/StyleCLIPDraw/master/images/fruit.jpg',\
                          num_iter=1000, style_opt_freq=5, style_opt_iter=50, debug=True) 
show_img(img)
```

I got this error 

```
/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    154     Variable._execution_engine.run_backward(
    155         tensors, grad_tensors_, retain_graph, create_graph, inputs,
--> 156         allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
    157 
    158 
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by pschaldenbrand** [comment]
Hi @mcanet , Sorry for the trouble.  The error comes from a versioning issue with torch.  It was resolved in a past issue (#2) but it appears that torch has since changed and that fix no longer works.  Could you please show what version of torch and torchvision you are running in your notebook? `!pip show torch torchvision`

I was able to resolve this error by running the following code to re-install torch with versions torch==1.7.1+cu110 and torchvision==0.8.2+cu110

```
import subprocess

CUDA_version = [s for s in subprocess.check_output(["nvcc", "--version"]).decode("UTF-8").split(", ") if s.startswith("release")][0].split(" ")[-1]
print("CUDA version:", CUDA_version)

if CUDA_version == "10.0":
    torch_version_suffix = "+cu100"
elif CUDA_version == "10.1":
    torch_version_suffix = "+cu101"
elif CUDA_version == "10.2":
    torch_version_suffix = "+cu102"
else:
    torch_version_suffix = "+cu110"

!pip install torch==1.7.1{torch_version_suffix} torchvision==0.8.2{torch_version_suffix} -f https://download.pytorch.org/whl/torch_stable.html ftfy regex
```

If this works for you as well, I'll update the notebook.  Please let me know if you get a chance to try it.  Thanks!

**Comment by mcanet** [comment]
Hi @pschaldenbrand,

This what I get with `!pip show torch torchvision`
```
Name: torch
Version: 1.10.0+cu111
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.7/dist-packages
Requires: typing-extensions
Required-by: torchvision, torchtext, torch-tools, fastai, clip
---
Name: torchvision
Version: 0.11.1+cu111
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: pillow, torch, numpy
Required-by: torch-tools, fastai, clip
```

Yes, it worked to me when I add it this too. 
See you in Neurips, I will attend to presentation of the paper.

**Comment by pschaldenbrand** [comment]
Sorry for the trouble, @mcanet .  Added the new install of torch code to the notebook 268e14e76514cce69f2d38814d91e42023ab281c

See you at NeurIPS!
